In [59]:
import os
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

In [128]:
environtmen_name = "LunarLander-v2"
env = gym.make(environtmen_name, render_mode = 'human')

In [120]:
environment_name = 'CartPole-v1'
env = gym.make(environment_name, render_mode='human')

In [122]:
def policy(observation):
    return env.action_space.sample()

observation, info = env.reset(seed=42)
for _ in range(1000):
   action = policy(observation)  # User-defined policy function
   observation, reward, terminated, truncated, info = env.step(action)

   if terminated or truncated:
      observation, info = env.reset()
#env.close()

In [118]:
env.close()

In [80]:
observation

array([-2.3680945e-01, -7.9739332e-04,  1.4337078e-04, -2.6851931e-06,
        4.1385359e-04, -4.1012339e-05,  1.0000000e+00,  1.0000000e+00],
      dtype=float32)

In [82]:
reward

-100

In [84]:
terminated

True

In [86]:
truncated

True

In [88]:
info

{}

In [25]:
env.action_space.sample()

0

In [27]:
env.action_space

Discrete(4)

In [33]:
env.action_space

Discrete(2)

In [130]:
env.close()

In [15]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, truncated, info = env.step(action)
        score += reward
        done = done or truncated
        env.render()
    print('episode: {} Score: {}'.format(episode, score))
#env.close()

episode: 1 Score: -240.2774045191661
episode: 2 Score: -133.99656163593045
episode: 3 Score: -144.97704135749822
episode: 4 Score: -136.9513982693845
episode: 5 Score: -51.42240600559475


In [104]:
env.close()

In [65]:
environment_name = 'CartPole-v0'
env = gym.make(environment_name, render_mode='human')

C:\Users\Owen\anaconda3\Lib\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(


In [67]:
environment_name

'CartPole-v0'

In [69]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, truncated, info = env.step(action)
        score += reward
        done = done or truncated
        env.render()
    print('episode: {} Score: {}'.format(episode, score))
#env.close()

episode: 1 Score: 16.0
episode: 2 Score: 11.0
episode: 3 Score: 25.0
episode: 4 Score: 10.0
episode: 5 Score: 26.0


In [83]:
env.close()

In [13]:
episodes = 5
for episode in range(1, episodes+1):
    print(episode)

1
2
3
4
5


In [15]:
env.reset()

error: display Surface quit

In [20]:
env.action_space

Discrete(2)

In [22]:
env.action_space.sample()

1

In [24]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [26]:
env.step(1)

error: display Surface quit

In [28]:
env.action_space

Discrete(2)

In [30]:
env.action_space.sample()

0

In [32]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [34]:
env.observation_space.sample()

array([ 8.5330468e-01, -1.9129247e+38,  3.0518800e-01,  4.0405397e+37],
      dtype=float32)

In [71]:
log_path = os.path.join('Training', 'Logs')

In [73]:
log_path

'Training\\Logs'

In [40]:
from stable_baselines3 import PPO

In [110]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log = log_path)

Using cpu device


In [77]:
PPO??

Init signature:
PPO(
    policy: Union[str, type[stable_baselines3.common.policies.ActorCriticPolicy]],
    env: Union[gymnasium.core.Env, ForwardRef('VecEnv'), str],
    learning_rate: Union[float, Callable[[float], float]] = 0.0003,
    n_steps: int = 2048,
    batch_size: int = 64,
    n_epochs: int = 10,
    gamma: float = 0.99,
    gae_lambda: float = 0.95,
    clip_range: Union[float, Callable[[float], float]] = 0.2,
    clip_range_vf: Union[NoneType, float, Callable[[float], float]] = None,
    normalize_advantage: bool = True,
    ent_coef: float = 0.0,
    vf_coef: float = 0.5,
    max_grad_norm: float = 0.5,
    use_sde: bool = False,
    sde_sample_freq: int = -1,
    rollout_buffer_class: Optional[type[stable_baselines3.common.buffers.RolloutBuffer]] = None,
    rollout_buffer_kwargs: Optional[dict[str, Any]] = None,
    target_kl: Optional[float] = None,
    stats_window_size: int = 100,
    tensorboard_log: Optional[str] = None,
    policy_kwargs: Optional[dict[str, Any]]

In [89]:
model.learn(total_timesteps = 20000)

Logging to Training\Logs\PPO_3
-----------------------------
| time/              |      |
|    fps             | 44   |
|    iterations      | 1    |
|    time_elapsed    | 46   |
|    total_timesteps | 2048 |
-----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 42           |
|    iterations           | 2            |
|    time_elapsed         | 95           |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0073651043 |
|    clip_fraction        | 0.0686       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.687       |
|    explained_variance   | 0.0136       |
|    learning_rate        | 0.0003       |
|    loss                 | 5.71         |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.00917     |
|    value_loss           | 52.2         |
----------------------------

In [91]:
PPO_Path = os.path.join('Training', 'Saved Models', 'PPO_Model_Cartpole')

In [ ]:
model.learn(total_timesteps=1000)

## Evaluation

In [93]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

(200.0, 0.0)

In [104]:
env.close()

In [ ]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, truncated, info = env.step(action)
        score += reward
        done = done or truncated
        env.render()
    print('episode: {} Score: {}'.format(episode, score))
#env.close()

# Test

In [100]:
action, _ = model.predict(obs)

(array([1], dtype=int64), None)

In [102]:
action

(array([1], dtype=int64), None)

In [112]:
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action, _ = model.predict(obs)
        obs, reward, done, info = env.step(action)
        score += reward
    print('episode: {} Score: {}'.format(episode, score))

episode: 1 Score: [14.]
episode: 2 Score: [32.]
episode: 3 Score: [12.]
episode: 4 Score: [15.]
episode: 5 Score: [10.]


In [114]:
env.close()

In [116]:
 obs = env.reset()

In [118]:
model.predict(obs)

(array([0], dtype=int64), None)

In [122]:
model.predict??

Signature:
model.predict(
    observation: Union[numpy.ndarray, dict[str, numpy.ndarray]],
    state: Optional[tuple[numpy.ndarray, ...]] = None,
    episode_start: Optional[numpy.ndarray] = None,
    deterministic: bool = False,
) -> tuple[numpy.ndarray, typing.Optional[tuple[numpy.ndarray, ...]]]
Source:   
    def predict(
        self,
        observation: Union[np.ndarray, dict[str, np.ndarray]],
        state: Optional[tuple[np.ndarray, ...]] = None,
        episode_start: Optional[np.ndarray] = None,
        deterministic: bool = False,
    ) -> tuple[np.ndarray, Optional[tuple[np.ndarray, ...]]]:
        """
        Get the policy action from an observation (and optional hidden state).
        Includes sugar-coating to handle different observations (e.g. normalizing images).

        :param observation: the input observation
        :param state: The last hidden states (can be None, used in recurrent policies)
        :param episode_start: The last masks (can be None, used in r

In [124]:
training_log_path = os.path.join(log_path, 'PPO_2')
training_log_path

'Training\\Logs\\PPO_2'

In [126]:
!tensorboard --logdir=(training_log_path)

^C


In [128]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [130]:
save_path = os.path.join('Training', 'Saved Models')
log_path = os.path.join('Training', 'Logs')

In [132]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])

In [134]:
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=190, verbose=1)
eval_callback = EvalCallback(env, 
                             callback_on_new_best=stop_callback, 
                             eval_freq=10000, 
                             best_model_save_path=save_path, 
                             verbose=1)

In [136]:
model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log=log_path)

Using cpu device


In [138]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training\Logs\PPO_4
-----------------------------
| time/              |      |
|    fps             | 608  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 396         |
|    iterations           | 2           |
|    time_elapsed         | 10          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008929158 |
|    clip_fraction        | 0.0646      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.687      |
|    explained_variance   | -0.00491    |
|    learning_rate        | 0.0003      |
|    loss                 | 8.45        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.00967    |
|    value_loss           | 50.8        |
-----------------------------------------
---

In [140]:
model_path = os.path.join('Training', 'Saved Models', 'best_model')
model = PPO.load(model_path, env=env)

In [142]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

(200.0, 0.0)

In [144]:
env.close()

In [150]:
net_arch = [dict(pi=[128,128,128,128], vf=[128,128,128,128])]

In [152]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path, policy_kwargs={'net_arch':net_arch})

Using cpu device


C:\Users\Owen\anaconda3\Lib\site-packages\stable_baselines3\common\policies.py:486: UserWarning: As shared layers in the mlp_extractor are removed since SB3 v1.8.0, you should now pass directly a dictionary and not a list (net_arch=dict(pi=..., vf=...) instead of net_arch=[dict(pi=..., vf=...)])
  warnings.warn(


In [154]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training\Logs\PPO_5
-----------------------------
| time/              |      |
|    fps             | 578  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 273       |
|    iterations           | 2         |
|    time_elapsed         | 14        |
|    total_timesteps      | 4096      |
| train/                  |           |
|    approx_kl            | 0.0154528 |
|    clip_fraction        | 0.259     |
|    clip_range           | 0.2       |
|    entropy_loss         | -0.681    |
|    explained_variance   | 2.26e-05  |
|    learning_rate        | 0.0003    |
|    loss                 | 4.66      |
|    n_updates            | 10        |
|    policy_gradient_loss | -0.0318   |
|    value_loss           | 22.2      |
---------------------------------------
---------------------------------------

In [170]:
from stable_baselines3 import DQN

model = DQN('MlpPolicy', env, verbose = 1, tensorboard_log=log_path)
model.learn(total_timesteps=20000, callback=eval_callback)

Using cpu device


TypeError: DQN.learn() got an unexpected keyword argument 'render_mode'

In [158]:
dqn_path = os.path.join('Training', 'Saved Models', 'DQN_model')

In [162]:

model.save(dqn_path)

In [172]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

(9.0, 0.8944271909999159)